name: .NET Notts Blog Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        jekyll build